### PR TITLE
feat: support object,list(object) variable types

### PR DESCRIPTION
**Pull request by evanli18**
Closes: #233
Signed-off-by: Evan Li <evan.li97@outlook.com>

### CODE REVIEW

**Comment by evanli18** [comment]
ref: https://www.terraform.io/language/values/variables.

**Comment by zzxwill** [comment]
That's great. Please add some unit tests to cover the code change.

**Comment by evanli18** [comment]
> That's great. Please add some unit tests to cover the code change.

I fix the unit test.

**Review by zzxwill — APPROVED** [review]
This feature is significant! Thanks for your contribution.

**Pull request merged**
